name       : libbsd
version    : 0.10.0
release    : 4
source     :
    - https://libbsd.freedesktop.org/releases/libbsd-0.10.0.tar.xz : 34b8adc726883d0e85b3118fa13605e179a62b31ba51f676136ecb2d0bc1a887
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - BSD-4-Clause
summary    : BSD functionality library
component  : system.utils
description: |
    This library provides useful functions commonly found on BSD systems, and lacking on others like GNU systems, thus making it easier to port projects with strong BSD origins, without needing to embed the same code over and over again on each project.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
