name       : libbsd
version    : 0.8.0
release    : 2
source     :
    - http://libbsd.freedesktop.org/releases/libbsd-0.8.0.tar.xz : fbb732084bd960e4c78b688aac875be98e290cc6fe462b2ff8ee946a6473e38c
license    :
    - BSD-3-Clause
    - BSD-4-Clause
    - BSD-2-Clause
summary    : BSD functionality library
component   : system.utils
description: |
    This library provides useful functions commonly found on BSD systems, and lacking on others like GNU systems, thus making it easier to port projects with strong BSD origins, without needing to embed the same code over and over again on each project.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
